module Yescode
  class NotFoundError < StandardError
  end

  class ServerError < StandardError
  end

  class Router
    attr_accessor self.logger: Logger?

    def initialize: -> void
    def call: (Hash[untyped, untyped] env) -> [Integer, Hash[untyped, untyped], untyped]

    private

    def find_route: (String path_info) -> [Class | Symbol | nil, Hash[untyped, untyped] | nil]
  end
end
