source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "mail", "2.7.1"
gem "net-smtp", "0.3.1"
gem "rack", "2.2.3"
gem "rack_csrf", "2.6.0"
gem "sqlite3", "1.4.2"
gem "tipi", "0.52"
gem "yescode", path: "~/Projects/yescode"
