class YesRoutes
  attr_accessor self.paths: Hash[[Symbol, Symbol], String]
  attr_accessor self.routes: Hash[String, Array[Yescode::Route]]

  def self.match: (String verb, String path_string, Symbol class_name, Symbol method_name) -> void
  def self.path: (Symbol class_name, Symbol method_name, ?(Hash[Symbol, String] | YesRecord)  params) -> String
  def self.get: (String path_string, Symbol class_name, Symbol method_name) -> void
  def self.post: (String path_string, Symbol class_name, Symbol method_name) -> void
  def self.resource: (String path_string, Symbol class_name) -> void
  def self.sub_params_in_path: (String path, ?Hash[untyped, untyped] params) -> String
  def self.add_route: (Yescode::Route route) -> void
end
