# TypeProf 0.21.2

# Classes
class YesView
  self.@template_path: bot
  self.@layout: bot
  self.@template_name: untyped

  def self.template_path: -> String
  def self.layout: -> String
  def self.template: -> String
  def self.view: (untyped template_name) -> untyped
  def self.template_name: -> String
  attr_accessor csrf_name: bot
  attr_accessor csrf_value: bot
  attr_accessor assets: bot
  attr_accessor session: bot
  attr_accessor ajax: bot
  def template: -> String
  def render: (untyped tmpl, ?Hash[untyped, untyped] params) -> untyped
  def csrf_field: -> String
  def form: (?Hash[untyped, untyped] params) -> String
  def _form: -> String
  def form_link: (untyped str, untyped controller_name, untyped method_name, ?Hash[untyped, untyped] params) -> String
  def css: -> Array[untyped]
  def js: -> Array[untyped]
  def path: (untyped class_name, untyped method_name, ?Hash[untyped, untyped] params) -> untyped
  def fetch: (untyped class_name, untyped method_name, ?Hash[untyped, untyped] params) -> String
end
