class YesRoutes
  attr_accessor self.routes: Array[[String, Class]]
  attr_accessor self.paths: Hash[Class, String]

  def self.route: (String path_string, Class class_name) -> void
  def self.path: (Class class_name, ?(Hash[untyped, untyped] | YesRecord | nil) params) -> String

  private

  def self.sub_params_in_path: (String path, ?Hash[untyped, untyped] params) -> String
end
