#!/usr/bin/env ruby

# frozen_string_literal: true

require "yescode"

HELP_MESSAGE = <<~TXT
  Usage: yescode <command> [options]

  Supported yescode commands:
    scaffold      Generate a migration, query, routes, model and components
    component     Generate a blank component
    migration     Generate a migration
    migrate       Migrates the database with up sql in ./db/migrations/*.sql
    rollback      Rolls the database back with down sql in ./db/migrations/*.sql

    new           Create a new Yescode application

    Example:
      yescode new my_app

    This will create a new application in ./my_app
TXT

command, *args = ARGV

case command
when "new"
  Yescode::Generators::New.call(args[0])
when "component"
  Yescode::Generators::Component.new(args[0]).call
when "scaffold"
  Yescode::Generators::Scaffold.new(args).call
when "migration"
  Yescode::Generators::Migration.new(args[0]).call
when "migrate"
  YesApp.migrate
when "rollback"
  YesApp.rollback(args[0] || 1)
when "-v", "--version"
  puts Yescode::VERSION
when "-h", "--help"
  puts HELP_MESSAGE
else
  puts HELP_MESSAGE
end
